The search bar now displays an 'x' to clear the search text once ther…
abhinav12k/Drunkyard pull request #7
Opened 2023-01-17 02:02 UTC by nathanmeade

…e has actually been some input. The keyboard now disappears when the checkmark is selected on the users keyboard after typing their search text.

2023-01-19 18:28 UTC, abhinav12k requested changes

2023-01-19 18:28 UTC, abhinav12k commented on app/src/main/java/com/abhinav12k/drunkyard/presentation/drinkList/components/SearchBar.kt
>          val focusManager = LocalFocusManager.current
remove the local variable and use the one declared outside of if condition

2023-01-19 18:28 UTC, abhinav12k commented on app/src/main/java/com/abhinav12k/drunkyard/presentation/drinkList/components/SearchBar.kt
> +            when { value.isNotEmpty() ->
Use a if statement in case there is only one / two possible outcome.

2023-01-19 18:55 UTC, nathanmeade commented on app/src/main/java/com/abhinav12k/drunkyard/presentation/drinkList/components/SearchBar.kt
> +            when { value.isNotEmpty() ->
When statement has now been replaced by an if statement.

2023-01-19 18:55 UTC, nathanmeade commented on app/src/main/java/com/abhinav12k/drunkyard/presentation/drinkList/components/SearchBar.kt
>          val focusManager = LocalFocusManager.current
This duplicate focusManager variable has now been deleted.

2023-01-20 17:45 UTC, abhinav12k approved these changes

2023-01-20 17:48 UTC, merged

2023-01-20 18:39 UTC, nathanmeade commented
@abhinav12k I'm not sure if you have access but the branch can be deleted as well. If not I can do it.

2023-01-20 18:47 UTC, abhinav12k commented
As this branch is on your forked project. You can only delete that branch.

2023-01-20 18:50 UTC, nathanmeade commented
> As this branch is on your forked project. You can only delete that branch.

Good to know. Branch has now been deleted.